package xushun.bookstore.model;

/**
 * SecondType generated by MyEclipse Persistence Tools
 */

public class SecondType implements java.io.Serializable {

	// Fields

	private Integer typeId;
	private Integer superId;
	private String typeName;
	private Long lastModifyTime;
	
	private FirstType superType;

	// Constructors

	/** default constructor */
	public SecondType() {
	}

	/** full constructor */
	public SecondType(Integer superId, String typeName, Long lastModifyTime) {
		this.superId = superId;
		this.typeName = typeName;
		this.lastModifyTime = lastModifyTime;
	}

	// Property accessors

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Integer getSuperId() {
		return this.superId;
	}

	public void setSuperId(Integer superId) {
		this.superId = superId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Long getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	public FirstType getSuperType() {
		return superType;
	}

	public void setSuperType(FirstType superType) {
		this.superType = superType;
	}
	
	
}